### ISSUE TITLE
图5中的train all指的是什么意思，和train adaptors之间的区别是什么

### ISSUE THREAD

**Issue by NingBoB** [DoctorKey/Practise#3]
有幸读到您的文章，读完收获颇丰，但是仍有一些不懂的地方。

**Comment by NingBoB** [comment]
另外对公式2和3存在疑问，τ的值越大表明需要剪枝吗，但是计算中latMo-latMp应该是值越大，延迟越低，这与公式3中定义的s值越小，其剪枝优先度更高是不是矛盾了

**Comment by DoctorKey** [comment]
train all表示训练模型的所有参数，train adaptors表示只训练adaptors的参数

**Comment by NingBoB** [comment]
> train all表示训练模型的所有参数，train adaptors表示只训练adaptors的参数

噢噢，了解了，感谢
